"""
============================================================
GER
S29-E5.5
Numerical Pathology Audit
============================================================

Objective
---------
Perform a detailed numerical audit of every fitted model used
during S29-E5.3 in order to determine whether numerical
pathologies affect the scientific conclusions.

This experiment DOES NOT execute any new bootstrap.

It analyses only the outputs already generated by:

    S29-E5.3
    S29-E5.4

Outputs
-------

numerical_pathology_report.txt

model_stability.csv

model_pathology_counts.csv

winner_stability_report.csv

pair_reclassification.csv

final_certificate.txt
"""

from pathlib import Path
import json

import numpy as np
import pandas as pd


# ============================================================
# GOOGLE DRIVE
# ============================================================

DRIVE_ROOT = Path("/content/drive/MyDrive")

if not DRIVE_ROOT.exists():
    raise RuntimeError(
        "\nGoogle Drive not mounted.\n"
    )

print("[OK] Google Drive detected.")


# ============================================================
# INPUT
# ============================================================

INPUT_E53 = (
    DRIVE_ROOT
    / "GER_RESULTS"
    / "S29_E5.3"
    / "massive_validation"
)

INPUT_E54 = (
    DRIVE_ROOT
    / "GER_RESULTS"
    / "S29_E5.4"
    / "bootstrap_robustness_audit"
)

BOOTSTRAP_FILE = INPUT_E53 / "bootstrap_results.jsonl"

PAIR_REPORT = INPUT_E54 / "pair_quality_report.csv"

ROBUST_STATS = INPUT_E54 / "robust_statistics.csv"

DEGENERATE = INPUT_E54 / "degenerate_cases.csv"


required = [

    BOOTSTRAP_FILE,

    PAIR_REPORT,

    ROBUST_STATS,

    DEGENERATE,

]

for file in required:

    if not file.exists():

        raise RuntimeError(

            f"\nRequired file not found:\n\n{file}"

        )


# ============================================================
# OUTPUT
# ============================================================

OUTPUT = (
    DRIVE_ROOT
    / "GER_RESULTS"
    / "S29_E5.5"
    / "numerical_pathology_audit"
)

OUTPUT.mkdir(

    parents=True,

    exist_ok=True,

)

MODEL_COUNTS = OUTPUT / "model_pathology_counts.csv"

MODEL_STABILITY = OUTPUT / "model_stability.csv"

PAIR_RECLASSIFICATION = OUTPUT / "pair_reclassification.csv"

WINNER_REPORT = OUTPUT / "winner_stability_report.csv"

REPORT = OUTPUT / "numerical_pathology_report.txt"

CERTIFICATE = OUTPUT / "final_certificate.txt"

print(f"[OK] Input  E5.3 : {INPUT_E53}")
print(f"[OK] Input  E5.4 : {INPUT_E54}")
print(f"[OK] Output      : {OUTPUT}")


# ============================================================
# HEADER
# ============================================================

print("=" * 70)
print("GER")
print("S29-E5.5")
print("Numerical Pathology Audit")
print("=" * 70)
print()


# ============================================================
# LOAD DATA
# ============================================================

records = []

with open(BOOTSTRAP_FILE, "r") as f:

    for line in f:

        records.append(json.loads(line))


pair_df = pd.read_csv(PAIR_REPORT)

robust_df = pd.read_csv(ROBUST_STATS)

degenerate_df = pd.read_csv(DEGENERATE)

print(f"Pairs loaded           : {len(records)}")
print(f"Robust statistics rows : {len(robust_df)}")
print(f"Degenerate pairs       : {len(degenerate_df)}")
print()


# ============================================================
# LIMITS
# ============================================================

EXTREME_R2 = -100.0

HIGH_MAD = 1.0

LOW_QUALITY = 70.0


# ============================================================
# CONTAINERS
# ============================================================

model_rows = []

stability_rows = []

pair_rows = []

winner_rows = []

print("Auditing numerical pathologies...")
print()
# ============================================================
# MODEL AUDIT
# ============================================================

for record in records:

    x_name = record["X"]
    y_name = record["Y"]

    pair_name = f"{x_name} <-> {y_name}"

    winner = record["winner_model"]

    probability = record["winner_probability"]

    print(pair_name)

    winner_changed = False

    best_valid_model = None

    best_valid_score = -np.inf

    # --------------------------------------------------------
    # Iterate over every fitted model
    # --------------------------------------------------------

    for model in record["r2_statistics"]:

        r2 = record["r2_statistics"][model]

        mean = r2.get("mean", np.nan)
        median = r2.get("median", np.nan)
        std = r2.get("std", np.nan)
        q025 = r2.get("q025", np.nan)
        q975 = r2.get("q975", np.nan)

        invalid = False

        if not np.isfinite(mean):
            invalid = True

        if not np.isfinite(median):
            invalid = True

        if not np.isfinite(std):
            invalid = True

        if not np.isfinite(q025):
            invalid = True

        if not np.isfinite(q975):
            invalid = True

        extreme_r2 = False

        finite_values = [

            v for v in

            [mean, median, q025, q975]

            if np.isfinite(v)

        ]

        if len(finite_values):

            if np.min(finite_values) < EXTREME_R2:

                extreme_r2 = True

        parameter_explosion = False

        if model in record["parameter_statistics"]:

            for parameter in record["parameter_statistics"][model]:

                for value in parameter.values():

                    if not np.isfinite(value):

                        parameter_explosion = True

                        continue

                    if abs(value) > 1e12:

                        parameter_explosion = True

        pathological = (

            invalid

            or

            extreme_r2

            or

            parameter_explosion

        )

        if not pathological:

            if np.isfinite(median):

                if median > best_valid_score:

                    best_valid_score = median

                    best_valid_model = model

        model_rows.append({

            "Pair": pair_name,

            "Model": model,

            "Winner": model == winner,

            "MeanR2": mean,

            "MedianR2": median,

            "StdR2": std,

            "MAD": abs(mean - median)
            if np.isfinite(mean)
            and np.isfinite(median)
            else np.nan,

            "ExtremeR2": extreme_r2,

            "InvalidStatistics": invalid,

            "ParameterExplosion": parameter_explosion,

            "Pathological": pathological

        })

    if best_valid_model is None:

        best_valid_model = winner

    if best_valid_model != winner:

        winner_changed = True

    pair_rows.append({

        "Pair": pair_name,

        "OriginalWinner": winner,

        "ReclassifiedWinner": best_valid_model,

        "WinnerChanged": winner_changed,

        "WinnerProbability": probability

    })

    winner_rows.append({

        "Pair": pair_name,

        "Stable": not winner_changed,

        "OriginalWinner": winner,

        "ValidatedWinner": best_valid_model

    })
  # ============================================================
# MODEL SUMMARIES
# ============================================================

model_df = pd.DataFrame(model_rows)

pair_result_df = pd.DataFrame(pair_rows)

winner_df = pd.DataFrame(winner_rows)

summary_rows = []

for model in sorted(model_df["Model"].unique()):

    subset = model_df[
        model_df["Model"] == model
    ]

    total = len(subset)

    invalid = int(
        subset["InvalidStatistics"].sum()
    )

    extreme = int(
        subset["ExtremeR2"].sum()
    )

    explosions = int(
        subset["ParameterExplosion"].sum()
    )

    pathological = int(
        subset["Pathological"].sum()
    )

    winners = int(
        subset["Winner"].sum()
    )

    valid = total - pathological

    stability = (

        100.0 * valid / total

        if total

        else 0.0

    )

    summary_rows.append({

        "Model": model,

        "Occurrences": total,

        "WinnerOccurrences": winners,

        "ValidFits": valid,

        "PathologicalFits": pathological,

        "InvalidStatistics": invalid,

        "ExtremeR2": extreme,

        "ParameterExplosions": explosions,

        "StabilityIndex": stability

    })

summary_df = pd.DataFrame(summary_rows)

summary_df = summary_df.sort_values(

    "StabilityIndex",

    ascending=False

)

# ============================================================
# PAIR RECLASSIFICATION
# ============================================================

quality_map = dict(

    zip(

        pair_df["X"] + " <-> " + pair_df["Y"],

        pair_df["QualityIndex"]

    )

)

reclassification = []

for _, row in pair_result_df.iterrows():

    pair = row["Pair"]

    quality = quality_map.get(

        pair,

        np.nan

    )

    if row["WinnerChanged"]:

        status = "RECLASSIFIED"

    else:

        if np.isnan(quality):

            status = "UNKNOWN"

        elif quality >= 95:

            status = "ROBUST"

        elif quality >= LOW_QUALITY:

            status = "ROBUST_WITH_WARNINGS"

        else:

            status = "NUMERICAL_PATHOLOGY"

    reclassification.append({

        "Pair": pair,

        "QualityIndex": quality,

        "OriginalWinner": row["OriginalWinner"],

        "ValidatedWinner": row["ReclassifiedWinner"],

        "WinnerChanged": row["WinnerChanged"],

        "Status": status

    })

reclassification_df = pd.DataFrame(

    reclassification

)

# ============================================================
# SAVE CSV FILES
# ============================================================

summary_df.to_csv(

    MODEL_COUNTS,

    index=False

)

summary_df.to_csv(

    MODEL_STABILITY,

    index=False

)

winner_df.to_csv(

    WINNER_REPORT,

    index=False

)

reclassification_df.to_csv(

    PAIR_RECLASSIFICATION,

    index=False

)
# ============================================================
# GLOBAL RESULTS
# ============================================================

total_models = len(model_df)

total_pathological = int(
    model_df["Pathological"].sum()
)

total_invalid = int(
    model_df["InvalidStatistics"].sum()
)

total_extreme = int(
    model_df["ExtremeR2"].sum()
)

total_explosions = int(
    model_df["ParameterExplosion"].sum()
)

stable_winners = int(
    winner_df["Stable"].sum()
)

changed_winners = len(winner_df) - stable_winners

robust_pairs = int(
    np.sum(
        reclassification_df["Status"] == "ROBUST"
    )
)

warning_pairs = int(
    np.sum(
        reclassification_df["Status"]
        == "ROBUST_WITH_WARNINGS"
    )
)

pathological_pairs = int(
    np.sum(
        reclassification_df["Status"]
        == "NUMERICAL_PATHOLOGY"
    )
)

reclassified_pairs = int(
    np.sum(
        reclassification_df["Status"]
        == "RECLASSIFIED"
    )
)

# ============================================================
# NUMERICAL REPORT
# ============================================================

with open(REPORT, "w") as f:

    f.write("GER S29-E5.5\n")
    f.write("Numerical Pathology Audit\n\n")

    f.write(
        f"Pairs analysed              : {len(records)}\n"
    )

    f.write(
        f"Models analysed             : {total_models}\n"
    )

    f.write(
        f"Pathological models         : {total_pathological}\n"
    )

    f.write(
        f"Invalid statistics          : {total_invalid}\n"
    )

    f.write(
        f"Extreme R²                 : {total_extreme}\n"
    )

    f.write(
        f"Parameter explosions        : {total_explosions}\n\n"
    )

    f.write(
        f"Stable winners              : {stable_winners}\n"
    )

    f.write(
        f"Changed winners             : {changed_winners}\n\n"
    )

    f.write(
        f"Robust pairs                : {robust_pairs}\n"
    )

    f.write(
        f"Robust with warnings        : {warning_pairs}\n"
    )

    f.write(
        f"Numerical pathology         : {pathological_pairs}\n"
    )

    f.write(
        f"Reclassified pairs          : {reclassified_pairs}\n"
    )

# ============================================================
# FINAL CERTIFICATE
# ============================================================

with open(CERTIFICATE, "w") as f:

    f.write("GER S29-E5.5\n")
    f.write("FINAL NUMERICAL CERTIFICATE\n")
    f.write("=" * 50 + "\n\n")

    if changed_winners == 0:

        f.write(
            "Winner Stability : PASS\n\n"
        )

    else:

        f.write(
            "Winner Stability : FAIL\n\n"
        )

    if total_explosions == 0:

        f.write(
            "Parameter Stability : PASS\n"
        )

    else:

        f.write(
            "Parameter Stability : WARNING\n"
        )

    if total_invalid == 0:

        f.write(
            "Numerical Integrity : PASS\n"
        )

    else:

        f.write(
            "Numerical Integrity : WARNING\n"
        )

    f.write("\n")

    if (

        changed_winners == 0

        and

        total_explosions == 0

        and

        total_invalid == 0

    ):

        verdict = "ROBUST"

    elif changed_winners == 0:

        verdict = "ROBUST WITH NUMERICAL WARNINGS"

    else:

        verdict = "REQUIRES FURTHER INVESTIGATION"

    f.write(
        f"FINAL VERDICT : {verdict}\n"
    )

# ============================================================
# FINAL SCREEN REPORT
# ============================================================

print()

print("=" * 70)
print("Numerical pathology audit completed.")
print("=" * 70)

print()

print("Generated files")

print(" ", MODEL_COUNTS)
print(" ", MODEL_STABILITY)
print(" ", WINNER_REPORT)
print(" ", PAIR_RECLASSIFICATION)
print(" ", REPORT)
print(" ", CERTIFICATE)

print()

print("Experiment completed.")

# ============================================================
# END
# ============================================================
