"""
============================================================
GER
S29-E6.2.8
OBSERVABLE SPACE STRUCTURAL CERTIFICATE
============================================================

Objective
---------
Generate the certified structural description of the
Observable Space produced throughout the complete S29-E6.2
pipeline.

This experiment performs no additional geometric analysis.
Instead, it validates, integrates and certifies all results
generated by experiments E6.2.1.1 through E6.2.7.1 into a
single scientific artifact representing the certified state
of the Observable Space.

The Structural Certificate becomes the official interface
between the E6.2 series and all subsequent GER experiments.

Execution
---------
python -m GER_CORE.S29.S29_E6_2_8_observable_space_structural_certificate

Author
------
Eduardo Batista de Freitas
GER Project
"""

from pathlib import Path
import json

import pandas as pd


# ============================================================
# INPUT
# ============================================================

BASE = Path(
    "/content/drive/MyDrive/GER_RESULTS/S29_E6.2"
)

BOUNDING = (
    BASE
    / "E6_2_1_BoundingGeometry"
    / "scientific_certificate.json"
)

DENSITY = (
    BASE
    / "E6_2_2_DensityField"
    / "density_certificate.json"
)

CONCENTRATION = (
    BASE
    / "E6_2_3_ConcentrationAnalysis"
    / "concentration_certificate.json"
)

RELATIONAL = (
    BASE
    / "E6_2_4_RelationalOrganization"
    / "relational_certificate.json"
)

OCCUPANCY = (
    BASE
    / "E6_2_5_OccupancyStructure"
    / "occupancy_certificate.json"
)

STABILITY = (
    BASE
    / "E6_2_6_StabilityAnalysis"
    / "stability_certificate.json"
)

OUTLIER = (
    BASE
    / "E6_2_7_StructuralOutlierAnalysis"
    / "outlier_certificate.json"
)

OUTLIER_PROFILE = (
    BASE
    / "E6_2_7_StructuralOutlierAnalysis"
    / "outlier_profile.csv"
)

PERIPHERALITY = (
    BASE
    / "E6_2_7_1_StructuralPeripherality"
    / "peripherality_certificate.json"
)

PERIPHERALITY_PROFILE = (
    BASE
    / "E6_2_7_1_StructuralPeripherality"
    / "peripherality_profile.csv"
)


# ============================================================
# OUTPUT
# ============================================================

OUT = (
    BASE
    / "E6_2_8_ObservableSpaceStructuralCertificate"
)

OUT.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# Banner
# ============================================================

print("=" * 70)
print("GER")
print("S29-E6.2.8")
print("Observable Space Structural Certificate")
print("=" * 70)


# ============================================================
# Load Certificates
# ============================================================

def load_json(path):

    with open(path, "r", encoding="utf-8") as f:

        return json.load(f)


bounding = load_json(BOUNDING)
density = load_json(DENSITY)
concentration = load_json(CONCENTRATION)
relational = load_json(RELATIONAL)
occupancy = load_json(OCCUPANCY)
stability = load_json(STABILITY)
outlier = load_json(OUTLIER)
peripherality = load_json(PERIPHERALITY)

ranking = pd.read_csv(OUTLIER_PROFILE)
periphery = pd.read_csv(PERIPHERALITY_PROFILE)

print("[OK] Bounding Certificate")
print("[OK] Density Certificate")
print("[OK] Concentration Certificate")
print("[OK] Relational Certificate")
print("[OK] Occupancy Certificate")
print("[OK] Stability Certificate")
print("[OK] Outlier Certificate")
print("[OK] Peripherality Certificate")

print()

print(
    f"Certified Observables : {relational['observables']}"
)

print(
    f"Geometric Nucleus : {relational['geometric_nucleus']}"
)

print()


# ============================================================
# Structural Certificate
# ============================================================

structural_certificate = {

    # --------------------------------------------------------
    # Metadata
    # --------------------------------------------------------

    "experiment": "S29-E6.2.8",

    "title": "Observable Space Structural Certificate",

    "status": "CERTIFIED",

    # --------------------------------------------------------
    # Global Geometry
    # --------------------------------------------------------

    "observables":

        relational["observables"],

    "geometric_nucleus":

        relational["geometric_nucleus"],

    "bounding_radius":

        bounding["bounding_radius"],

    "hyperbox_volume":

        bounding["hyperbox_volume"],

    "compactness":
    
        bounding["compactness_index"],

        # --------------------------------------------------------
    # Density
    # --------------------------------------------------------

    "mean_density":

        density["mean_density"],

    "maximum_density":

        density["maximum_density"],

    "minimum_density":

        density["minimum_density"],

    # --------------------------------------------------------
    # Concentration
    # --------------------------------------------------------

    "central_observable":

        concentration["central_observable"],

    "most_concentrated":

        concentration["most_concentrated_observable"],

    "mean_concentration":

        concentration["mean_concentration"],

    # --------------------------------------------------------
    # Relational Organization
    # --------------------------------------------------------

    "structural_levels":

        relational["structural_levels"],

    "most_peripheral":

        relational["most_peripheral_observable"],

    "maximum_distance":

        relational["maximum_distance_to_nucleus"],

    # --------------------------------------------------------
    # Occupancy
    # --------------------------------------------------------

    "coverage":

        occupancy["coverage"],

    "occupancy_index":

        occupancy["occupancy_index"],

    # --------------------------------------------------------
    # Stability
    # --------------------------------------------------------

    "stability_index":

        stability["stability_index"],

    "radial_regularity":

        stability["radial_regularity"],

    "structural_balance":

        stability["structural_balance"],

    # --------------------------------------------------------
    # Structural Singularities
    # --------------------------------------------------------

    "top_structural_outlier":

        outlier["top_structural_outlier"],

    "highest_outlier_score":

        outlier["highest_outlier_score"],

    "mean_outlier_score":

        outlier["mean_outlier_score"],

    # --------------------------------------------------------
    # Structural Peripherality
    # --------------------------------------------------------

    "most_peripheral_observable":

        peripherality["most_peripheral_observable"],

    "least_peripheral_observable":

        peripherality["least_peripheral_observable"],

    "maximum_peripherality":

        peripherality["maximum_peripherality"],

    "mean_peripherality":

        peripherality["mean_peripherality"]

}


# ============================================================
# Top Structural Singularities
# ============================================================

top5_outliers = ranking[
    [
        "OutlierRank",
        "Observable",
        "OutlierScore"
    ]
].head(5)

top5_outliers.to_csv(
    OUT / "top_structural_singularities.csv",
    index=False
)


# ============================================================
# Top Structural Periphery
# ============================================================

top5_periphery = periphery[
    [
        "PeripheralRank",
        "Observable",
        "PeripheralityScore"
    ]
].head(5)

top5_periphery.to_csv(
    OUT / "top_structural_periphery.csv",
    index=False
)


# ============================================================
# Save Certificate
# ============================================================

with open(
    OUT / "observable_space_certificate.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        structural_certificate,
        f,
        indent=4
    )


# ============================================================
# Console Summary
# ============================================================

print("=" * 70)
print("Observable Space Certificate")
print("=" * 70)

print(f"Certified Observables : {structural_certificate['observables']}")
print(f"Geometric Nucleus     : {structural_certificate['geometric_nucleus']}")
print(f"Structural Levels     : {structural_certificate['structural_levels']}")
print(f"Coverage              : {structural_certificate['coverage']:.6f}")
print(f"Stability Index       : {structural_certificate['stability_index']:.6f}")

print(f"Top Outlier           : {structural_certificate['top_structural_outlier']}")
print(f"Most Peripheral       : {structural_certificate['most_peripheral_observable']}")

print()

# ============================================================
# Scientific Report
# ============================================================

with open(
    OUT / "observable_space_certificate_report.txt",
    "w",
    encoding="utf-8"
) as f:

    f.write("GER\n")
    f.write("S29-E6.2.8\n")
    f.write("Observable Space Structural Certificate\n")
    f.write("=" * 60 + "\n\n")

    f.write("CERTIFIED OBSERVABLE SPACE\n")
    f.write("--------------------------\n\n")

    f.write(f"Observables                 : {structural_certificate['observables']}\n")
    f.write(f"Geometric Nucleus           : {structural_certificate['geometric_nucleus']}\n")
    f.write(f"Structural Levels           : {structural_certificate['structural_levels']}\n")
    f.write(f"Bounding Radius             : {structural_certificate['bounding_radius']:.6f}\n")
    f.write(f"Hyperbox Volume             : {structural_certificate['hyperbox_volume']:.6f}\n")
    f.write(f"Compactness                 : {structural_certificate['compactness']:.6f}\n")

    f.write(f"Coverage                    : {structural_certificate['coverage']:.6f}\n")
    f.write(f"Occupancy Index             : {structural_certificate['occupancy_index']:.6f}\n")

    f.write(f"Stability Index             : {structural_certificate['stability_index']:.6f}\n")
    f.write(f"Radial Regularity           : {structural_certificate['radial_regularity']:.6f}\n")
    f.write(f"Structural Balance          : {structural_certificate['structural_balance']:.6f}\n")

    f.write(f"Mean Density                : {structural_certificate['mean_density']:.6f}\n")
    f.write(f"Mean Concentration          : {structural_certificate['mean_concentration']:.6f}\n")

    f.write(f"Top Structural Outlier      : {structural_certificate['top_structural_outlier']}\n")
    f.write(f"Highest Outlier Score       : {structural_certificate['highest_outlier_score']:.6f}\n")

    f.write(f"Most Peripheral Observable  : {structural_certificate['most_peripheral_observable']}\n")
    f.write(f"Least Peripheral Observable : {structural_certificate['least_peripheral_observable']}\n")
    f.write(f"Mean Peripherality          : {structural_certificate['mean_peripherality']:.6f}\n")
    f.write(f"Maximum Peripherality       : {structural_certificate['maximum_peripherality']:.6f}\n")

    f.write("\n")

    f.write("Top Structural Singularities\n")
    f.write("----------------------------\n\n")

    for _, row in top5_outliers.iterrows():

        f.write(
            f"{int(row['OutlierRank']):2d}  "
            f"{row['Observable']:<20}"
            f"Score={row['OutlierScore']:.6f}\n"
        )

    f.write("\n")

    f.write("Top Structural Periphery\n")
    f.write("------------------------\n\n")

    for _, row in top5_periphery.iterrows():

        f.write(
            f"{int(row['PeripheralRank']):2d}  "
            f"{row['Observable']:<20}"
            f"Score={row['PeripheralityScore']:.6f}\n"
        )

    f.write("\n")

    f.write("Scientific Conclusion\n")
    f.write("---------------------\n\n")

    f.write(
        "The S29-E6.2 pipeline successfully established a "
        "complete certified geometric description of the "
        "Observable Space. The experiments progressively "
        "identified the admissible geometric dimensions, "
        "characterized the global geometry, quantified local "
        "density and concentration, determined the intrinsic "
        "geometric nucleus, organized the relational "
        "hierarchy, measured occupancy and structural "
        "stability, identified structural singularities, "
        "and independently quantified structural "
        "peripherality. "
        "The resulting Structural Certificate represents "
        "the official certified state of the Observable "
        "Space and constitutes the certified interface "
        "between the E6.2 series and all subsequent GER "
        "experiments."
    )


# ============================================================
# Final Console Summary
# ============================================================

print("=" * 70)
print("Observable Space Structural Certificate")
print("=" * 70)

print(f"Observables          : {structural_certificate['observables']}")
print(f"Geometric Nucleus    : {structural_certificate['geometric_nucleus']}")
print(f"Structural Levels    : {structural_certificate['structural_levels']}")

print(f"Coverage             : {structural_certificate['coverage']:.6f}")
print(f"Stability Index      : {structural_certificate['stability_index']:.6f}")

print(f"Top Outlier          : {structural_certificate['top_structural_outlier']}")
print(f"Most Peripheral      : {structural_certificate['most_peripheral_observable']}")

print()
print("Structural Certificate: CERTIFIED")

print()
print("Results saved to:")
print(OUT)

print("=" * 70)


# ============================================================
# Main
# ============================================================

def main():
    """Main entry point."""
    pass


if __name__ == "__main__":
    main()
