"""
============================================================
GER CORE
RH-E0
Spectral Spacing Exploration
============================================================

Objective
---------
First observational experiment for the Relational Spectral
Geometry framework.

This experiment performs no comparison with Random Matrix
Theory and makes no assumptions about the Riemann
Hypothesis.

Its only purpose is to inspect the spectrum naturally
generated by the GER operator.

Outputs
-------
- Eigenvalue list
- Spectral gaps
- Basic statistics
- Gap histogram

Author
------
Eduardo Batista de Freitas

Version
-------
1.0
"""

from __future__ import annotations

import numpy as np
import matplotlib.pyplot as plt

from GER.CORE.ger_engine import run_engine


# ============================================================
# Experiment
# ============================================================

print("=" * 60)
print("GER RH-E0")
print("Spectral Spacing Exploration")
print("=" * 60)

# ------------------------------------------------------------
# Run GER
# ------------------------------------------------------------

result = run_engine()

eigenvalues = np.asarray(result["eigenvalues"], dtype=float)

# ------------------------------------------------------------
# Sort spectrum
# ------------------------------------------------------------

eigenvalues = np.sort(eigenvalues)

# ------------------------------------------------------------
# Spectral gaps
# ------------------------------------------------------------

gaps = np.diff(eigenvalues)

# ------------------------------------------------------------
# Report
# ------------------------------------------------------------

print()
print("Spectrum")
print("-" * 60)

print(f"Number of eigenvalues : {len(eigenvalues)}")
print(f"Minimum eigenvalue    : {eigenvalues.min():.12f}")
print(f"Maximum eigenvalue    : {eigenvalues.max():.12f}")

print()
print("Gap Statistics")
print("-" * 60)

print(f"Minimum gap : {gaps.min():.12e}")
print(f"Maximum gap : {gaps.max():.12e}")
print(f"Mean gap    : {gaps.mean():.12e}")
print(f"Std gap     : {gaps.std():.12e}")

# ------------------------------------------------------------
# First eigenvalues
# ------------------------------------------------------------

print()
print("First 20 Eigenvalues")
print("-" * 60)

for value in eigenvalues[:20]:
    print(f"{value:.12f}")

# ------------------------------------------------------------
# First gaps
# ------------------------------------------------------------

print()
print("First 20 Gaps")
print("-" * 60)

for value in gaps[:20]:
    print(f"{value:.12e}")

# ------------------------------------------------------------
# Histogram
# ------------------------------------------------------------

plt.figure(figsize=(8,5))

plt.hist(
    gaps,
    bins=40,
)

plt.title("Spectral Gap Distribution")
plt.xlabel("Gap")
plt.ylabel("Frequency")

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

print()
print("=" * 60)
print("Experiment Finished")
print("=" * 60)
