"""
============================================================
GER CORE
RH-E1
Spectral Degeneracy Analysis
============================================================

Objective
---------
Investigate the intrinsic degeneracy structure of the
spectrum generated by the GER operator.

This experiment does not modify the operator.

It only measures:

- Eigenvalue multiplicities
- Number of distinct eigenvalues
- Degeneracy distribution
- Maximum multiplicity

Author
------
Eduardo Batista de Freitas

Version
-------
1.0
"""

from __future__ import annotations

import numpy as np
import matplotlib.pyplot as plt

from collections import Counter

from GER.CORE.ger_engine import run_engine


print("=" * 60)
print("GER RH-E1")
print("Spectral Degeneracy Analysis")
print("=" * 60)

# ------------------------------------------------------------
# Run GER
# ------------------------------------------------------------

result = run_engine()

eigenvalues = np.asarray(result["eigenvalues"], dtype=float)

# ------------------------------------------------------------
# Numerical tolerance
# ------------------------------------------------------------

rounded = np.round(eigenvalues, 12)

counter = Counter(rounded)

distinct = sorted(counter.items())

multiplicities = np.array(
    [m for _, m in distinct],
    dtype=int,
)

print()
print("Spectrum Summary")
print("-" * 60)

print(f"Total eigenvalues   : {len(eigenvalues)}")
print(f"Distinct values     : {len(distinct)}")
print(f"Maximum multiplicity: {multiplicities.max()}")
print(f"Mean multiplicity   : {multiplicities.mean():.3f}")

print()
print("First 30 Distinct Eigenvalues")
print("-" * 60)

for value, mult in distinct[:30]:
    print(f"{value:18.12f}   multiplicity = {mult}")

print()
print("Multiplicity Distribution")
print("-" * 60)

distribution = Counter(multiplicities)

for mult in sorted(distribution):
    print(
        f"Multiplicity {mult:2d} : "
        f"{distribution[mult]} eigenvalues"
    )

# ------------------------------------------------------------
# Histogram
# ------------------------------------------------------------

plt.figure(figsize=(7,5))

plt.hist(
    multiplicities,
    bins=np.arange(
        multiplicities.min(),
        multiplicities.max()+2
    )-0.5,
)

plt.xlabel("Multiplicity")
plt.ylabel("Frequency")
plt.title("Spectral Degeneracy Distribution")

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

print()
print("=" * 60)
print("Experiment Finished")
print("=" * 60)
