# ============================================================
# GER
#
# S27-R0.1
#
# External State Definition
#
# Formal definition of the state γ for external
# dynamical systems.
#
# ============================================================


def main():

    print("=" * 60)
    print("GER")
    print("S27-R0.1")
    print("External State Definition")
    print("=" * 60)
    print()

    print("QUESTION")
    print("-" * 60)

    print(
        "What is the mathematical object represented by "
        "the GER state γ when the observed system is "
        "external to the GER engine?"
    )

    print()

    print("CURRENT GER INTERPRETATION")
    print("-" * 60)

    print(
        "Inside the GER engine, γ is the scalar field "
        "defined over the vertices of the relational graph."
    )

    print()

    print("GENERALIZED INTERPRETATION")
    print("-" * 60)

    print(
        "γ is interpreted as a state vector belonging to "
        "a finite-dimensional vector space V."
    )

    print()

    print(
        "The GER observatory does not require γ to be "
        "generated by the relational engine."
    )

    print()

    print(
        "It only requires γ to admit projection onto "
        "a compatible modal basis."
    )

    print()

    print("MATHEMATICAL REQUIREMENTS")
    print("-" * 60)

    requirements = [

        "γ belongs to a finite-dimensional vector space.",

        "γ completely represents the observed state.",

        "γ admits linear projection onto a modal basis.",

        "Modal coefficients can be normalized.",

        "Spectral observables are well defined.",

    ]

    for i, r in enumerate(requirements, start=1):

        print(f"{i}. {r}")

    print()

    print("WORKING HYPOTHESIS")
    print("-" * 60)

    print(
        "The observational domain of GER consists of "
        "dynamic systems admitting a state vector γ "
        "that can be represented in a compatible "
        "modal basis."
    )

    print()

    print("=" * 60)
    print("STATUS : STATE DEFINITION PROPOSED")
    print("=" * 60)


if __name__ == "__main__":

    main()
